// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbW5Ab0733uphlI1ZzWuGlPDq02R-BAys',
    appId: '1:841847566784:web:6edb3913f7cc1f7a859825',
    messagingSenderId: '841847566784',
    projectId: 'quizzone-fa878',
    authDomain: 'quizzone-fa878.firebaseapp.com',
    storageBucket: 'quizzone-fa878.firebasestorage.app',
    measurementId: 'G-K31ZNEJVH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWnuzYI6v2XJQIoBUJ5h9KGvwO6ljtgtQ',
    appId: '1:841847566784:android:f5af0ccaa59e5fb0859825',
    messagingSenderId: '841847566784',
    projectId: 'quizzone-fa878',
    storageBucket: 'quizzone-fa878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewKXVA4P3BSOrME2SFcZbHPBBQg_8JBw',
    appId: '1:841847566784:ios:16c5015745d6b156859825',
    messagingSenderId: '841847566784',
    projectId: 'quizzone-fa878',
    storageBucket: 'quizzone-fa878.firebasestorage.app',
    iosBundleId: 'com.example.quizZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewKXVA4P3BSOrME2SFcZbHPBBQg_8JBw',
    appId: '1:841847566784:ios:16c5015745d6b156859825',
    messagingSenderId: '841847566784',
    projectId: 'quizzone-fa878',
    storageBucket: 'quizzone-fa878.firebasestorage.app',
    iosBundleId: 'com.example.quizZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbW5Ab0733uphlI1ZzWuGlPDq02R-BAys',
    appId: '1:841847566784:web:c9d7f1441372faf1859825',
    messagingSenderId: '841847566784',
    projectId: 'quizzone-fa878',
    authDomain: 'quizzone-fa878.firebaseapp.com',
    storageBucket: 'quizzone-fa878.firebasestorage.app',
    measurementId: 'G-XWHE4HD12F',
  );
}
